### ISSUE TITLE
Support web components

### ISSUE THREAD

**Issue by aelbore** [rixo/rollup-plugin-hot#2]
- was able to load and hot reload basic web components but  theres an error. it logs the error but after 1 or 2 secs it will disappear the error log.
<img width="636" alt="Screenshot 2020-01-29 at 10 42 12 PM" src="https://user-images.githubusercontent.com/18069807/73369926-60afb900-42ee-11ea-8d37-3170d19a97b0.png">

**Comment by rixo** [comment]
Thanks for reporting. Indeed, I havent considered web components support yet.

Are you using this with Svelte, or standalone somehow?

Your screenshot makes it pretty apparent what the (current) problem is... Do you happen to have any idea how this could be solved? Is there a way to redefine a component with the same name? Otherwise, the only solution I can think of for now would be to implement some sort of HMR proxy for... custom element names?

Do you have some project you can share with which I could experiment? I don't have any real experience with web components...

**Comment by aelbore** [comment]
@rixo thanks for this initiative
i fork the repo and will check 
heres the repo just go to example folder i added `hello-world.js` custom-elements
https://github.com/ngx-devtools/rollup-plugin-hot

i tried to add if condition but still doesn't work
```
if (!customElements.get('hello-world')) {
  customElements.define('hello-world', HelloWorld)
}
```
not sure yet how you reload the component.
the error says that the component is already define, maybe check if the component is existing then remove it and thats the time to reload it. (just an idea) ^^

**Comment by rixo** [comment]
I've sent a [PR to your example repo](https://github.com/ngx-devtools/rollup-plugin-hot/pull/1), with some hack that solves your precise example.

Unfortunately, the conclusion is that it's probably not feasible to support HMR for web components in a general way. At the very least, we need a way to be able to tell the component that it needs to rerender (because the underlying code would have been replaced by HMR).

What are you trying to accomplish with your web components? Some kind of generic tool? Or rather some kind of UI framework for which we could rely on some assumptions to make HMR work with it?

In any case, I think this kind of support should live in a framework specific plugin (like for example my Svelte HMR adapter, or React hot loader in Webpack).

**Comment by rixo** [comment]
@aelbore Still working on this? Should we close?

**Comment by aelbore** [comment]
@rixo you can close this, your workaround works but i havent look into deep.
by the way many thanks
